### ISSUE TITLE
Set xml filetype automatically

### ISSUE THREAD

**Issue by JulioJu** [sharat87/roast.vim#16]
Hi !

Actually on the web, there are two famous format for API : JSON and XML. 

Actually this plugin doesn't support XML (doesn't automatically set the correct file type)

An example :

`GET http://lookup.dbpedia.org/api/search/KeywordSearch?QueryClass=place&QueryString=berlin`

Furthermore, it could be cool if it could be linted automatically as  `vim-rest-console` do (see https://github.com/diepm/vim-rest-console/blob/7b407f47185468d1b57a8bd71cdd66c9a99359b2/ftplugin/rest.vim#L5 )

Thanks in advance

:-)

**Comment by sharat87** [comment]
I just pushed a commit to add XML support. This was on my list forever so, thanks for reminding. Please test it out and let me know.

As for linting it, I think that falls out of the scope of roast a bit. I'd like to focus on just the http-client part. Linting can easily be done with one of the other such plugins that excel at it like Syntastic or Ale. May be we can explore an integration with those so that they are invoked right after a request is finished.

**Comment by JulioJu** [comment]
Yes it works, thanks !
